name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'
      release_name:
        description: 'Release name'
        required: true
        default: 'Release'

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Create proofs_of_concept.txt if it doesn't exist
      run: |
        mkdir -p src
        touch src/proofs_of_concept.txt
        
    - name: Run create_release.py
      run: python src/create_release.py
      
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add src/proofs_of_concept.txt
        git diff --staged --quiet || git commit -m "Update release info in proofs_of_concept.txt"
        git push
        
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.version }}
        release_name: ${{ github.event.inputs.release_name }} ${{ github.event.inputs.version }}
        draft: false
        prerelease: false
        body: |
          Release ${{ github.event.inputs.version }}
          
          This release was created automatically by running create_release.py
          
          ## Changes
          - Release created at: $(date)