name: Release VSCE Extension

on:
  workflow_dispatch:

jobs:
  release-vsce:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: jac/support/vscode_ext/jac/package-lock.json

      - name: Install vsce globally
        run: npm install --global @vscode/vsce

      - name: Install Dependencies & Package Extension
        working-directory: jac/support/vscode_ext/jac/
        run: |
          npm ci
          vsce package

      - name: Publish to VS Code Marketplace
        working-directory: jac/support/vscode_ext/jac/
        run: vsce publish -p $VSCE_TOKEN
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}

      - name: Get Extension Version
        id: get_version
        working-directory: jac/support/vscode_ext/jac/
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=v$VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release with VSIX Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: jac/support/vscode_ext/jac/
        run: |
          gh release create "${{ steps.get_version.outputs.version }}" \
            --title "VS Code Extension Release ${{ steps.get_version.outputs.version }}" \
            --notes "VS Code Extension Release ${{ steps.get_version.outputs.version }}

          This release was created automatically after publishing to VS Code Marketplace.

          ## Changes
          - Extension published to marketplace
          - VSIX file attached for manual installation" \
            *.vsix
